config/routes.rb
Rails.application.routes.draw do
  root   'users#home'
  # ヘルプページを作成する際はコメントを外す
# get    '/help',   to: 'static_pages#help'
  get    '/about',  to: 'static_pages#about'
  get    '/signup', to: 'users#new'
  post   '/signup', to: 'users#create'
  post   '/search', to: 'users#search'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    '/top',    to: 'microposts#top'
  post   '/trend',  to: 'microposts#trend'
  get    'password_resets/new'
  get    'password_resets/edit'
  resources :users do
    # 例: users/1/following
    member do
      get :activate, 
          :following, 
          :followers, 
          :favoriting_microposts
    end
  end
  resources :microposts do
    member do
      post :favorited_users, :shared_users, :show_picture
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :micropost_share_relationships,    only: [:create, :destroy]
  resources :micropost_favorite_relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/micropost_favorite_relationship.rb
class MicropostFavoriteRelationship < ApplicationRecord
    belongs_to :user,      class_name: User.name
    belongs_to :micropost, class_name: Micropost.name
    validates :user_id,      presence: true
    validates :micropost_id, presence: true
end

app/controllers/micropost_favorite_relationships_controller.rb
class MicropostFavoriteRelationshipsController < ApplicationController

    # micropostを取得できなかった場合のレンダリング先
    @@MISSING_RENDER_JS = 'missing_share_favorite'.freeze
  
    # POST micropost_favorite_relationships_path
    # フォロー
    def create    
      @micropost = Micropost.find(params[:micropost_id])
      current_user.favorite_micropost(@micropost)

      respond_to do |format|
        format.js
      end
    end
      
    # DELETE micropost_favorite_relationships_path(micropost)
    # フォロー解除
    def destroy
      mfr = MicropostFavoriteRelationship.find(params[:id])
      @micropost = mfr.micropost
      current_user.unfavorite_micropost(@micropost)

      respond_to do |format|
        format.js
      end
    end
  
  end

app/views/micropost_favorite_relationships/_favorite_micropost.html.erb
<%= form_with url: micropost_favorite_relationships_path, class: 'form_micropost' do |form| %>
    <%= form.hidden_field :micropost_id, :value => micropost.id %>
    <%= form.submit "お気に入り", id: "favorite_micropost_submit-#{ micropost.id }"%>
    <i class="fas fa-paw favorite_micropost_icon btn" value="<%= micropost.id %>" ></i>
<% end %>
<%= render 'micropost_favorite_relationships/favorited_users_count', { micropost: micropost } %>


app/views/micropost_favorite_relationships/_favorite_micropost_form.html.erb
<span class="favorite_micropost_form">
    <% if current_user.favoriting_micropost?(micropost) %>
        <%= render 'micropost_favorite_relationships/unfavorite_micropost', { micropost: micropost } %>
    <% else %>   
        <%= render 'micropost_favorite_relationships/favorite_micropost', { micropost: micropost } %>
    <% end %>
</span>

app/views/micropost_favorite_relationships/_favorited_users_count.html.erb
<% if micropost.favorited_users.count >= 1 %>
    <%= form_with url: favorited_users_micropost_path(micropost), class: 'form_micropost' do |form| %>
        <strong class="stat favorited_users_count btn pl-0" value="<%= micropost.id %>" >
            <%= micropost.favorited_users.count %>
        </strong>
        <%= form.submit "シェアユーザー一覧", class: 'submit_favorited_users', id: "favorited_users_submit_#{ micropost.id }" %>
    <% end %>
<% end %>

app/views/micropost_favorite_relationships/_unfavorite_micropost.html.erb
<%= form_with url: micropost_favorite_relationship_path(current_user.acticve_micropost_favorite_relationships.find_by(micropost_id: micropost.id)), 
              method: :delete, class: 'form_micropost' do |form| %>
    <%= form.submit "解除", id: "favorite_micropost_submit-#{ micropost.id }"%>
    <i class="fas fa-paw unfavorite_micropost_icon btn" value="<%= micropost.id %>" ></i>
<% end %>
<%= render 'micropost_favorite_relationships/favorited_users_count', { micropost: micropost } %>

app/views/micropost_favorite_relationships/create.js.erb
$("<%= "#micropost-#{@micropost.id}" %> > .micropost_functions > .favorite_micropost_form")
.html("<%= j(render('micropost_favorite_relationships/unfavorite_micropost', micropost: @micropost)) %>");


app/views/micropost_favorite_relationships/destroy.js.erb
$("<%= "#micropost-#{@micropost.id}" %> > .micropost_functions > .favorite_micropost_form")
.html("<%= j(render('micropost_favorite_relationships/favorite_micropost', micropost: @micropost)) %>");

app/views/micropost_favorite_relationships/missing_share_favorite.js.erb
alert('投稿が見つかりませんでした。')