config/routes.rb
Rails.application.routes.draw do
  root   'users#home'
  # ヘルプページを作成する際はコメントを外す
# get    '/help',   to: 'static_pages#help'
  get    '/about',  to: 'static_pages#about'
  get    '/signup', to: 'users#new'
  post   '/signup', to: 'users#create'
  post   '/search', to: 'users#search'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    '/top',    to: 'microposts#top'
  post   '/trend',  to: 'microposts#trend'
  get    'password_resets/new'
  get    'password_resets/edit'
  resources :users do
    # 例: users/1/following
    member do
      get :activate, 
          :following, 
          :followers, 
          :favoriting_microposts
    end
  end
  resources :microposts do
    member do
      post :favorited_users, :shared_users, :show_picture
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :micropost_share_relationships,    only: [:create, :destroy]
  resources :micropost_favorite_relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu_bar.html.erb
<ul class="list-group pt-2">
    <%= link_to "一覧", current_user, class: "list-group-item"%>
    <%= link_to "お気に入り", favoriting_microposts_user_path(current_user), class: "list-group-item"%>
    <%= link_to "注目", top_path,     class: "list-group-item"%>
    <%= link_to "検索", users_path,   class: "list-group-item"%>
</ul>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |form| %>
  <%= render 'shared/error_messages', object: form.object %>
  <div class="field">
    <%= form.text_area :content, rows: 12, maxlength: 140, placeholder: "ぷりーず" %>
    <ul class="pictures_field pl-0"></ul>
    <%= form.file_field :pictures, multiple: true, class: "file-input add_pictures" %>
    <label class="btn far fa-images add_pictures_icon" for="micropost_pictures"></label>
  </div>
<% end %>

app/views/shared/_microposts.html.erb
<% if @microposts.any? %>
  <ol class="microposts">
    <%= render @microposts %>
  </ol>
  <%= render 'microposts/show_users_modal' %>
  <%= render 'microposts/show_picture_modal' %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/shared/_user_info.html.erb
<h1>
    <%= image_tag @user.icon, class: 'user_info_icon' if @user.icon.attached? %>
    <%= image_tag 'TentanativeIcon.PNG', class: 'user_info_icon' unless @user.icon.attached? %>
    <%= @user.name %>
</h1>

app/views/shared/error_404.js.erb
alert('処理に失敗しました。\n存在しないアイテムを選択している可能性があります。');

app/views/shared/error_500.js.erb
alert('処理に失敗しました。\nプラウザを更新してください。');