config/routes.rb
Rails.application.routes.draw do
  root   'users#home'
  # ヘルプページを作成する際はコメントを外す
# get    '/help',   to: 'static_pages#help'
  get    '/about',  to: 'static_pages#about'
  get    '/signup', to: 'users#new'
  post   '/signup', to: 'users#create'
  post   '/search', to: 'users#search'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    '/top',    to: 'microposts#top'
  post   '/trend',  to: 'microposts#trend'
  get    'password_resets/new'
  get    'password_resets/edit'
  resources :users do
    # 例: users/1/following
    member do
      get :activate, 
          :following, 
          :followers, 
          :favoriting_microposts
    end
  end
  resources :microposts do
    member do
      post :favorited_users, :shared_users, :show_picture
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :micropost_share_relationships,    only: [:create, :destroy]
  resources :micropost_favorite_relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/micropost_share_relationship.rb
class MicropostShareRelationship < ApplicationRecord
    belongs_to :user,      class_name: User.name
    belongs_to :micropost, class_name: Micropost.name
    validates :user_id,      presence: true
    validates :micropost_id, presence: true
end

app/controllers/micropost_share_relationships_controller.rb
class MicropostShareRelationshipsController < ApplicationController

  # micropostを取得できなかった場合のレンダリング先
  @@MISSING_RENDER_JS = 'missing_share_favorite'.freeze

  # POST micropost_share_relationships_path
  # フォロー
  def create
    @micropost = Micropost.find(params[:micropost_id])
    current_user.share_micropost(@micropost)

    respond_to do |format|
      format.js
    end
  end
    
  # DELETE micropost_share_relationships_path(micropost)
  # フォロー解除
  def destroy
    msr = MicropostShareRelationship.find(params[:id])
    @micropost = msr.micropost
    current_user.unshare_micropost(@micropost)
    
    respond_to do |format|
        format.js
    end
  end

end

app/views/micropost_share_relationships/_share_micropost.html.erb
<%= form_with url: micropost_share_relationships_path do |form| %>
    <%= form.hidden_field :micropost_id, :value => micropost.id %>
    <%= form.submit "シェア", id: "share_micropost_submit-#{ micropost.id }"%>
    <i class="fas fa-retweet share_micropost_icon btn" value="<%= micropost.id %>" ></i>
<% end %>
<%= render 'micropost_share_relationships/shared_users_count', { micropost: micropost } %>

app/views/micropost_share_relationships/_share_micropost_form.html.erb
<span class="share_micropost_form">
    <% if current_user.sharering_micropost?(micropost) %>
        <%= render 'micropost_share_relationships/unshare_micropost', { micropost: micropost } %>
    <% else %>   
        <%= render 'micropost_share_relationships/share_micropost', { micropost: micropost } %>
    <% end %>
</span>

app/views/micropost_share_relationships/_shared_users_count.html.erb
<% if micropost.shared_users.count >= 1 %>
    <%= form_with url: shared_users_micropost_path(micropost), class: 'form_micropost' do |form| %>
        <strong class="stat shared_users_count btn pl-0" value="<%= micropost.id %>" >
            <%= micropost.shared_users.count %>
        </strong>
        <%= form.submit "シェアユーザー一覧", class: 'submit_shared_users', id: "shared_users_submit_#{ micropost.id }" %>
    <% end %>
<% else %>
    <span class="notdisplay_count"></span>
<% end %>

app/views/micropost_share_relationships/_unshare_micropost.html.erb
<%= form_with url: micropost_share_relationship_path(current_user.active_micropost_share_relationships.find_by(micropost_id: micropost.id)), 
              method: :delete, class: 'form_micropost' do |form| %>
    <%= form.submit "解除", id: "share_micropost_submit-#{ micropost.id }"%>
    <i class="fas fa-retweet unshare_micropost_icon btn" value="<%= micropost.id %>" ></i>
<% end %>
<%= render 'micropost_share_relationships/shared_users_count', { micropost: micropost } %>

app/views/micropost_share_relationships/create.js.erb
$("<%= "#micropost-#{@micropost.id}" %> > .micropost_functions > .share_micropost_form")
.html("<%= j(render('micropost_share_relationships/unshare_micropost', micropost: @micropost)) %>");


app/views/micropost_share_relationships/destroy.js.erb
$("<%= "#micropost-#{@micropost.id}" %> > .micropost_functions > .share_micropost_form")
.html("<%= j(render('micropost_share_relationships/share_micropost', micropost: @micropost)) %>");

app/views/micropost_share_relationships/missing_share_favorite.js.erb
alert('投稿が見つかりませんでした。')