config/routes.rb
Rails.application.routes.draw do
  root   'users#home'
  # ヘルプページを作成する際はコメントを外す
# get    '/help',   to: 'static_pages#help'
  get    '/about',  to: 'static_pages#about'
  get    '/signup', to: 'users#new'
  post   '/signup', to: 'users#create'
  post   '/search', to: 'users#search'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    '/top',    to: 'microposts#top'
  post   '/trend',  to: 'microposts#trend'
  get    'password_resets/new'
  get    'password_resets/edit'
  resources :users do
    # 例: users/1/following
    member do
      get :activate, 
          :following, 
          :followers, 
          :favoriting_microposts
    end
  end
  resources :microposts do
    member do
      post :favorited_users, :shared_users, :show_picture
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :micropost_share_relationships,    only: [:create, :destroy]
  resources :micropost_favorite_relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3">
    <div class="container">
        <div class="text-right text-muted">
            <%= link_to "このサイトについて", about_path, class: "text-muted" %>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-danger">
    <div class="container">
        <ul class="navbar-nav">
            <li><%= link_to "ホーム", root_path, id: "logo" %></li>
        </ul>
        <ul class="navbar-nav">
            わんにゃんぽっど
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item"><%= link_to "ヘルプ", '#', class: "nav-link" %></li>
            <% if logged_in? %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        アカウント <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "設定", edit_user_path(current_user) %></li>
                        <li class="divider"></li>
                        <li>
                            <%= link_to "ログアウト", logout_path, method: :delete %>
                        </li>
                    </ul>
                </li>
            <% else %>
                <li class="nav-item"><%= link_to "ログイン", login_path, class: "nav-link" %></li>
            <% end %>
        </ul>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>わんにゃんぽっど</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>